# SPDX-License-Identifier copyleft-next-0.3.1
---
kdevops_bootlinux: False
infer_uid_and_group: False

data_path: "/data"
data_user: "root"
data_group: "root"

data_device: "/dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_kdevops0"
data_fstype: "xfs"
data_label: "data"
data_fs_opts: "-L {{ disk_setup_label }}"

# Linux target defaults
target_linux_admin_name: "Hacker Amanda"
target_linux_admin_email: "devnull@kernel.org"
target_linux_git: "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
target_linux_shallow_depth: 0
target_linux_tree: "linux-stable"
target_linux_dir_path: "{{ data_path }}/{{ target_linux_tree }}"
kdevops_baseline_and_dev: False

target_linux_ref: "v4.19.133"
target_linux_delta_file:
target_linux_config: "config-{{ target_linux_ref }}"
make: "make"
# Once ansible v2.10 becomes available we can move on to using
# ansible_processor_nproc but that was merged in 2020:
# The commit is 34db57a47f875d11c4068567b9ec7ace174ec4cf
# introduce fact "ansible_processor_nproc": number of usable vcpus #66569
# https://github.com/ansible/ansible/pull/66569
target_linux_make_cmd: "{{ make }} -j{{ ansible_processor_vcpus }}"
target_linux_make_install_cmd: "{{ target_linux_make_cmd }} modules_install install"

uninstall_kernel_enable: False

# If defined we'll apply this delta for you.
# target_linux_extra_patch: foo.patch

bootlinux_b4_am_this_host: False

bootlinux_9p: False
bootlinux_targets: false
bootlinux_builder: false

kdevops_workflow_enable_cxl: False

bootlinux_cxl_test: False
bootlinux_tree_set_by_cli: False

bootlinux_artifacts_dir: "{{ topdir_path }}/workflows/linux/artifacts"
kernel_packages: []
workflow_linux_packaged: false

# A/B testing defaults
bootlinux_ab_same_ref: True
bootlinux_ab_different_ref: False

# Development kernel settings (used when bootlinux_ab_different_ref is True)
bootlinux_dev_tree: ""
target_linux_dev_ref: "master"
target_linux_dev_kernelrelease: ""
target_linux_dev_localversion: ""
bootlinux_tree_custom_kernelrelease: False
bootlinux_tree_custom_localversion: false
bootlinux_is_dev_node: False
bootlinux_debug_ref: "{{ lookup('env', 'DEBUG_REF') | default(false, true) | bool }}"
