---
# Install Docker on RHEL/CentOS/Fedora

- name: Install Docker prerequisites
  become: true
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repository
  become: true
  ansible.builtin.command:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  changed_when: false
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  become: true
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Install Python Docker library
  become: true
  ansible.builtin.yum:
    name:
      - python3-docker
    state: present

- name: Start and enable Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add current user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user != 'root'
