repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.4.0
    hooks:
      - id: ansible-lint
        entry: bash scripts/ansible-lint.sh
