---
# SPDX-License-Identifier: copyleft-next-0.3.1
- name: Enable a CodeReady Builder repo for this distribution
  when:
    - ansible_facts['distribution'] != "Fedora"
    - devconfig_custom_yum_repofile | default('', true) | length == 0
  block:
    - name: Select the RHEL CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "codeready-builder-for-rhel-{{ ansible_facts['distribution_major_version'] }}-{{ ansible_facts['architecture'] }}-rpms"
      when:
        - ansible_facts['distribution'] == 'RedHat'
        - kdevops_enable_guestfs|bool

    - name: Select the Oracle Linux CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "ol9_codeready_builder"
      when:
        - ansible_facts['distribution'] == 'OracleLinux'

    - name: Select the CentOS CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "crb"
      when:
        - ansible_facts['distribution'] == 'CentOS'

    - name: Query available RHUI repositories
      ansible.builtin.command:
        cmd: dnf repolist --all
      register: codeready_discovery
      changed_when: false
      when:
        - ansible_facts['distribution'] == 'RedHat'
        - kdevops_enable_terraform|bool

    - name: Select the discovered RHUI CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "{{ codeready_discovery.stdout_lines | map('split') | map('first') | select('match', 'codeready-builder.*-rhui-rpms$') | first }}"
      when:
        - codeready_discovery is defined
        - codeready_discovery is not skipped
        - codeready_discovery.stdout_lines | map('split') | map('first') | select('match', 'codeready-builder.*-rhui-rpms$') | list | length > 0

    - name: The distribution/provisioner combo isn't recognized
      ansible.builtin.fail:
        msg: The selection heuristic failed to find a CodeReady Builder repo.
      when:
        - codeready_repo is not defined

    - name: Enable the selected CodeReady Builder repo
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.command:
        argv:
          - "/usr/bin/dnf"
          - "config-manager"
          - "--enable"
          - "{{ codeready_repo }}"
      register: dnf_result
      changed_when: dnf_result is success
