---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Stop and remove all AI containers
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ ai_milvus_container_name }}"
    - "{{ ai_minio_container_name }}"
    - "{{ ai_etcd_container_name }}"
  when: ai_milvus_docker | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Remove Docker network
  community.docker.docker_network:
    name: "{{ ai_docker_network_name }}"
    state: absent
  when: ai_milvus_docker | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Remove Docker storage directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ai_docker_data_path }}"
    - "{{ ai_docker_etcd_data_path }}"
    - "{{ ai_docker_minio_data_path }}"
  when: ai_milvus_docker | bool
  become: true

- name: Remove benchmark results directory
  ansible.builtin.file:
    path: "{{ ai_benchmark_results_dir }}"
    state: absent
  become: true

- name: Remove Docker images (optional)
  community.docker.docker_image:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ ai_milvus_container_image_string }}"
    - "{{ ai_etcd_container_image_string }}"
    - "{{ ai_minio_container_image_string }}"
  when: ai_milvus_docker | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Display destroy completion message
  ansible.builtin.debug:
    msg: |
      AI benchmark environment completely destroyed.
      All data, containers, and results have been removed.
