---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Stop and remove all AI containers
  docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ ai_milvus_container_name }}"
    - "{{ ai_minio_container_name }}"
    - "{{ ai_etcd_container_name }}"
  when: ai_milvus_docker|bool
  ignore_errors: yes

- name: Remove Docker network
  docker_network:
    name: "{{ ai_docker_network_name }}"
    state: absent
  when: ai_milvus_docker|bool
  ignore_errors: yes

- name: Remove Docker storage directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ai_docker_data_path }}"
    - "{{ ai_docker_etcd_data_path }}"
    - "{{ ai_docker_minio_data_path }}"
  when: ai_milvus_docker|bool
  become: yes

- name: Remove benchmark results directory
  file:
    path: "{{ ai_benchmark_results_dir }}"
    state: absent
  become: yes

- name: Remove Docker images (optional)
  docker_image:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ ai_milvus_container_image_string }}"
    - "{{ ai_etcd_container_image_string }}"
    - "{{ ai_minio_container_image_string }}"
  when: ai_milvus_docker|bool
  ignore_errors: yes

- name: Display destroy completion message
  debug:
    msg: |
      AI benchmark environment completely destroyed.
      All data, containers, and results have been removed.
