---
- name: Include role create_data_partition
  include_role:
    name: create_data_partition
  tags: ['setup', 'data_partition']

- name: Include role common
  include_role:
    name: common
  when:
    - infer_uid_and_group|bool

- name: Ensure data_dir has correct ownership
  tags: ['setup']
  become: true
  # become_method: sudo  # sudo is the default, not needed
  ansible.builtin.file:
    path: "{{ data_path }}"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    recurse: false
    state: directory
    mode: '0755'

- name: Ensure Milvus-specific subdirectories have correct ownership
  tags: ['setup']
  become: true
  # become_method: sudo  # sudo is the default, not needed
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    recurse: true
    state: directory
    mode: '0755'
  loop:
    - "{{ data_path }}/milvus"
    - "{{ ai_vector_db_milvus_docker_data_path | default(data_path + '/milvus/data') }}"
    - "{{ ai_vector_db_milvus_docker_etcd_data_path | default(data_path + '/milvus/etcd') }}"
    - "{{ ai_vector_db_milvus_docker_minio_data_path | default(data_path + '/milvus/minio') }}"
    - "{{ data_path }}/ai-benchmark"
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Include Docker installation tasks
  ansible.builtin.include_tasks: install_docker.yml

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml

# Benchmarks are included via separate playbook call with proper tags
# They are not run during the initial setup phase
