---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Milvus storage setup
  when: ai_milvus_storage_enable|bool
  block:
    - name: Install filesystem utilities
      package:
        name:
          - xfsprogs
          - e2fsprogs
          - btrfs-progs
        state: present
      become: yes
      become_method: sudo

    - name: Check if device exists
      stat:
        path: "{{ ai_milvus_device }}"
      register: milvus_device_stat
      failed_when: not milvus_device_stat.stat.exists

    - name: Check if Milvus storage is already mounted
      command: mountpoint -q {{ ai_milvus_mount_point }}
      register: milvus_mount_check
      changed_when: false
      failed_when: false

    - name: Setup Milvus storage filesystem
      when: milvus_mount_check.rc != 0
      block:
        - name: Create Milvus mount point directory
          file:
            path: "{{ ai_milvus_mount_point }}"
            state: directory
            mode: '0755'
          become: yes
          become_method: sudo

        - name: Detect filesystem type from node name
          set_fact:
            detected_fstype: >-
              {%- if 'xfs' in inventory_hostname -%}
                xfs
              {%- elif 'ext4' in inventory_hostname -%}
                ext4
              {%- elif 'btrfs' in inventory_hostname -%}
                btrfs
              {%- else -%}
                {{ ai_milvus_fstype | default('xfs') }}
              {%- endif -%}
          when: ai_milvus_use_node_fs | default(false) | bool

        - name: Detect XFS parameters from node name
          set_fact:
            milvus_xfs_blocksize: >-
              {%- if '64k' in inventory_hostname -%}
                65536
              {%- elif '32k' in inventory_hostname -%}
                32768
              {%- elif '16k' in inventory_hostname -%}
                16384
              {%- else -%}
                {{ ai_milvus_xfs_blocksize | default(4096) }}
              {%- endif -%}
            milvus_xfs_sectorsize: >-
              {%- if '4ks' in inventory_hostname -%}
                4096
              {%- elif '512s' in inventory_hostname -%}
                512
              {%- else -%}
                {{ ai_milvus_xfs_sectorsize | default(4096) }}
              {%- endif -%}
          when:
            - ai_milvus_use_node_fs | default(false) | bool
            - detected_fstype | default(ai_milvus_fstype) == 'xfs'

        - name: Detect ext4 parameters from node name
          set_fact:
            milvus_ext4_opts: >-
              {%- if '16k' in inventory_hostname and 'bigalloc' in inventory_hostname -%}
                -F -b 4096 -C 16384 -O bigalloc
              {%- elif '4k' in inventory_hostname -%}
                -F -b 4096
              {%- else -%}
                {{ ai_milvus_ext4_mkfs_opts | default('-F') }}
              {%- endif -%}
          when:
            - ai_milvus_use_node_fs | default(false) | bool
            - detected_fstype | default(ai_milvus_fstype) == 'ext4'

        - name: Set final filesystem type
          set_fact:
            milvus_fstype: "{{ detected_fstype | default(ai_milvus_fstype | default('xfs')) }}"

        - name: Format device with XFS
          command: >
            mkfs.xfs -f
            -b size={{ milvus_xfs_blocksize | default(ai_milvus_xfs_blocksize | default(4096)) }}
            -s size={{ milvus_xfs_sectorsize | default(ai_milvus_xfs_sectorsize | default(4096)) }}
            {{ ai_milvus_xfs_mkfs_opts | default('') }}
            {{ ai_milvus_device }}
          when: milvus_fstype == "xfs"
          become: yes
          become_method: sudo

        - name: Format device with Btrfs
          command: mkfs.btrfs {{ ai_milvus_btrfs_mkfs_opts | default('-f') }} {{ ai_milvus_device }}
          when: milvus_fstype == "btrfs"
          become: yes
          become_method: sudo

        - name: Format device with ext4
          command: mkfs.ext4 {{ milvus_ext4_opts | default(ai_milvus_ext4_mkfs_opts | default('-F')) }} {{ ai_milvus_device }}
          when: milvus_fstype == "ext4"
          become: yes
          become_method: sudo

        - name: Mount Milvus storage filesystem
          mount:
            path: "{{ ai_milvus_mount_point }}"
            src: "{{ ai_milvus_device }}"
            fstype: "{{ milvus_fstype }}"
            opts: defaults,noatime
            state: mounted
          become: yes
          become_method: sudo

        - name: Add Milvus storage mount to fstab
          mount:
            path: "{{ ai_milvus_mount_point }}"
            src: "{{ ai_milvus_device }}"
            fstype: "{{ milvus_fstype }}"
            opts: defaults,noatime
            state: present
          become: yes
          become_method: sudo

    - name: Ensure Milvus directories exist with proper permissions
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      become: yes
      become_method: sudo
      loop:
        - "{{ ai_milvus_mount_point }}"
        - "{{ ai_milvus_mount_point }}/data"
        - "{{ ai_milvus_mount_point }}/etcd"
        - "{{ ai_milvus_mount_point }}/minio"

    - name: Display Milvus storage setup complete
      debug:
        msg: "Milvus storage has been prepared at: {{ ai_milvus_mount_point }} with filesystem: {{ milvus_fstype | default(ai_milvus_fstype | default('xfs')) }}"
