---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Filter enabled filesystem configurations
  set_fact:
    enabled_fs_configs: "{{ ai_multifs_configurations | selectattr('enabled', 'equalto', true) | list }}"

- name: Run AI benchmarks on each filesystem configuration
  include_tasks: run_single_filesystem.yml
  loop: "{{ enabled_fs_configs }}"
  loop_control:
    loop_var: fs_config
    index_var: fs_index
  when: enabled_fs_configs | length > 0

- name: Generate multi-filesystem comparison report
  include_tasks: generate_comparison.yml
  when: enabled_fs_configs | length > 1
