---
- name: Update apt cache
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: true
  tags: vllm

- name: Install vLLM system dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - git
      - curl
      - wget
      - python3
      - python3-venv
      - docker.io
      - ca-certificates
      - gnupg
      - lsb-release
      - apt-transport-https
      - iptables
      - conntrack
    state: present
    update_cache: true
  tags: ["vllm", "deps"]

- name: Install Python development dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - build-essential
    state: present
  tags: ["vllm", "deps"]

- name: Install Python benchmarking dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - python3-aiohttp
      - python3-numpy
      - python3-pandas
      - python3-matplotlib
    state: present
  tags: ["vllm", "deps", "benchmark"]

- name: Install Python Kubernetes client library
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - python3-kubernetes
    state: present
  tags: ["vllm", "deps"]

- name: Add kdevops user to docker group
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: kdevops
    groups: docker
    append: yes
  tags: ["vllm", "deps", "docker-config"]
