---
# Install minimal dependencies needed for kernel installation on Debian
# This is used when bootlinux_9p is enabled and the build happens on the host

- name: Update apt cache accepting release info changes
  become: true
  become_method: sudo
  ansible.builtin.command:
    cmd: apt-get update --allow-releaseinfo-change
  changed_when: false
  ignore_errors: true

- name: Update apt cache
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: true

- name: Install minimal build tools for kernel installation
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - make
      - gcc
      - kmod
      - ccache
    state: present

- name: Install .deb package build dependencies for 9P package generation
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - debhelper-compat
      - libdw-dev
      - dpkg-dev
    state: present
    update_cache: true
  retries: 3
  delay: 5
  register: debpkg_result
  until: debpkg_result is succeeded
  when:
    - bootlinux_9p_build_packages|default(false)|bool
