---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- name: Include monitor_run tasks
  include_tasks: monitor_run.yml
  when:
    - enable_monitoring|default(false)|bool
  tags: [ 'monitoring', 'monitor_run' ]

- name: Include monitor_collect tasks
  include_tasks: monitor_collect.yml
  when:
    - enable_monitoring|default(false)|bool
  tags: [ 'monitoring', 'monitor_collect' ]
