---
# SPDX-License-Identifier: copyleft-next-0.3.1
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  failed_when: false
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  tags: vars

- name: Verify local build QEMU installation
  ansible.builtin.stat:
    path: "{{ qemu_bin_path }}"
  register: qemu_present
  changed_when: false
  failed_when: qemu_present.stat.exists and not qemu_present.stat.executable
  tags: ["qemu", "verify"]

- name: Install build-deps for QEMU as per each Linux distribution
  ansible.builtin.include_tasks: install-deps/main.yml
  when:
    - qemu_force_install_if_present|bool or not qemu_present.stat.exists

- name: Assume we won't build QEMU first
  ansible.builtin.set_fact:
    qemu_build_now: false
  tags: vars

- name: Annotate when we are building QEMU
  ansible.builtin.set_fact:
    qemu_build_now: true
  when:
    - qemu_force_install_if_present|bool or not qemu_present.stat.exists
  tags: vars

- name: Ensure the local development path exists
  ansible.builtin.file:
    path: "{{ local_dev_path }}"
    state: directory
    mode: "0755"
  tags: ["qemu", "build-deps"]
  when:
    - qemu_build_now|bool

- name: Fetch the QEMU git tree
  environment:
    GIT_SSL_NO_VERIFY: "true"
  ansible.builtin.git:
    repo: "{{ qemu_git }}"
    dest: "{{ qemu_data }}"
    version: "{{ qemu_version }}"
  when:
    - qemu_build_now|bool

- name: Nuke old build directory
  ansible.builtin.file:
    path: "{{ qemu_build_dir }}"
    state: absent
  tags: ["qemu", "build-deps"]
  when:
    - qemu_build_now|bool

- name: Pre-fetch QEMU subprojects so configure can disable downloads
  ansible.builtin.command: "meson subprojects download"
  changed_when: true
  tags: ["qemu", "configure"]
  args:
    chdir: "{{ qemu_data }}"
  when:
    - qemu_build_now|bool

- name: Run configure for QEMU
  ansible.builtin.command: "./configure --target-list={{ qemu_target }} --disable-download"
  changed_when: true
  tags: ["qemu", "configure"]
  args:
    chdir: "{{ qemu_data }}"
  when:
    - qemu_build_now|bool

- name: Get the number of build jobs
  ansible.builtin.command: "{{ num_jobs }}"
  changed_when: false
  tags: ["qemu", "configure", "build"]
  register: qemu_nproc
  when:
    - qemu_build_now|bool

- name: Build QEMU
  community.general.make:
    chdir: "{{ qemu_data }}"
    jobs: "{{ qemu_nproc.stdout }}"
  tags: ["qemu", "build"]
  when:
    - qemu_build_now|bool

- name: Install QEMU
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.command: "{{ make }} install"
  changed_when: true
  args:
    chdir: "{{ qemu_data }}"
  tags: ["qemu", "install"]
  when:
    - qemu_build_now|bool
