---
# SPDX-License-Identifier: copyleft-next-0.3.1
- name: reload nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
