---
# Configure Docker to use /data for storage to avoid filling up root filesystem

- name: Ensure /data/docker directory exists
  ansible.builtin.file:
    path: /data/docker
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Check if Docker daemon.json exists
  ansible.builtin.stat:
    path: /etc/docker/daemon.json
  register: docker_daemon_config

- name: Read existing Docker daemon configuration
  ansible.builtin.slurp:
    src: /etc/docker/daemon.json
  register: docker_daemon_json
  when: docker_daemon_config.stat.exists

- name: Parse existing Docker daemon configuration
  set_fact:
    docker_config: "{{ docker_daemon_json.content | b64decode | from_json }}"
  when: docker_daemon_config.stat.exists

- name: Initialize Docker configuration if not exists
  set_fact:
    docker_config: {}
  when: not docker_daemon_config.stat.exists

- name: Check if Docker mirror is available
  ansible.builtin.stat:
    path: /mirror/docker
  register: docker_mirror_check

- name: Auto-detect Docker mirror registry endpoint via 9P mount
  set_fact:
    docker_registry_mirrors:
      - "http://{{ ansible_default_ipv4.gateway }}:5000"
    docker_insecure_registries:
      - "{{ ansible_default_ipv4.gateway }}:5000"
    docker_mirror_type: "9p_mount"
  when:
    - docker_mirror_check.stat.exists
    - docker_mirror_check.stat.isdir

- name: Auto-detect Docker mirror registry endpoint via IP
  ansible.builtin.uri:
    url: "http://{{ ansible_default_ipv4.gateway }}:5000/v2/_catalog"
    method: GET
    timeout: 5
  register: mirror_registry_check
  failed_when: false
  when:
    - not docker_mirror_check.stat.exists
    - docker_registry_mirrors is not defined

- name: Set Docker registry mirror configuration via IP
  set_fact:
    docker_registry_mirrors:
      - "http://{{ ansible_default_ipv4.gateway }}:5000"
    docker_insecure_registries:
      - "{{ ansible_default_ipv4.gateway }}:5000"
    docker_mirror_type: "ip_gateway"
  when:
    - not docker_mirror_check.stat.exists
    - mirror_registry_check.status | default(0) == 200

- name: Display Docker mirror auto-detection result
  debug:
    msg: >-
      Docker mirror auto-detection:
      {% if docker_registry_mirrors is defined %}
      ✅ Found Docker mirror at {{ docker_registry_mirrors[0] }}
      ({{ docker_mirror_type | default('unknown') }}) - will use for faster image pulls
      {% elif docker_mirror_check.stat.exists %}
      ⚠️  Docker mirror directory exists but registry not accessible
      {% else %}
      ℹ️  No Docker mirror detected - using Docker Hub directly
      {% endif %}

- name: Update Docker configuration with data-root and optional registry mirrors
  set_fact:
    docker_config: >-
      {{ docker_config | combine({'data-root': '/data/docker'}) |
         combine({
           'registry-mirrors': docker_registry_mirrors,
           'insecure-registries': docker_insecure_registries
         }, recursive=True)
         if docker_registry_mirrors is defined
         else docker_config | combine({'data-root': '/data/docker'}) }}

- name: Configure Docker daemon to use /data
  ansible.builtin.copy:
    content: "{{ docker_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: '0644'
    owner: root
    group: root
    backup: yes
  become: yes
  register: docker_daemon_updated

- name: Stop Docker service
  ansible.builtin.systemd:
    name: docker
    state: stopped
  become: yes
  when: docker_daemon_updated.changed

# Handle existing Docker data if present
- name: Check if old Docker data exists
  ansible.builtin.stat:
    path: /var/lib/docker
  register: old_docker_data

- name: Check if Docker data directory has content
  ansible.builtin.find:
    paths: /var/lib/docker
    file_type: any
    recurse: no
  register: docker_content
  when: old_docker_data.stat.exists and old_docker_data.stat.isdir

- name: Move existing Docker data to /data (if any exists)
  ansible.builtin.shell:
    cmd: "cp -a /var/lib/docker/. /data/docker/ && rm -rf /var/lib/docker"
  become: yes
  when:
    - docker_daemon_updated.changed
    - old_docker_data.stat.exists
    - old_docker_data.stat.isdir
    - docker_content.matched | default(0) > 0

- name: Remove empty Docker data directory
  ansible.builtin.file:
    path: /var/lib/docker
    state: absent
  become: yes
  when:
    - docker_daemon_updated.changed
    - old_docker_data.stat.exists
    - docker_content.matched | default(0) == 0

- name: Start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    daemon_reload: yes
  become: yes
  when: docker_daemon_updated.changed

- name: Ensure Docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

# Configure minikube to use /data as well
- name: Ensure /data/minikube directory exists with correct ownership
  ansible.builtin.file:
    path: /data/minikube
    state: directory
    mode: '0755'
    owner: kdevops
    group: kdevops
    recurse: yes
  become: yes

# Ensure vLLM specific directories use /data
- name: Create vLLM data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: kdevops
    group: kdevops
  become: yes
  loop:
    - /data/vllm
    - /data/vllm/models
    - /data/vllm/cache
    - /data/vllm-benchmark
