---
# SPDX-License-Identifier: copyleft-next-0.3.1
- name: Debian user enablement
  ansible.builtin.include_tasks: enable-user/debian/main.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: SuSE user enablement
  ansible.builtin.include_tasks: enable-user/suse/main.yml
  when: ansible_facts['os_family'] == 'Suse'

- name: Red Hat family user enablement
  ansible.builtin.include_tasks: enable-user/redhat/main.yml
  when:
    - ansible_facts['os_family'] == 'RedHat'
