---
- include_role:
    name: create_data_partition
  tags: [ 'setup', 'data_partition' ]

- include_role:
    name: common
  when:
    - infer_uid_and_group|bool

- name: Ensure data_dir has correct ownership
  tags: [ 'setup' ]
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: "{{ data_path }}"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    recurse: yes
    state: directory

- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Install Docker if using Docker deployment
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes
  when: ai_milvus_docker|bool
  become: yes

- name: Add user to docker group
  user:
    name: "{{ data_user | default(ansible_user_id) }}"
    groups: docker
    append: yes
  when: ai_milvus_docker|bool
  become: yes

- name: Install Python dependencies for AI benchmarks
  pip:
    name:
      - pymilvus>=2.3.0
      - numpy
      - scikit-learn
      - pandas
      - tqdm
    state: present
  when: ai_benchmark_enable_graphing|bool

- name: Install additional Python dependencies for graphing
  pip:
    name:
      - matplotlib
      - seaborn
      - plotly
    state: present
  when: ai_benchmark_enable_graphing|bool

- name: Install filesystem utilities for XFS
  apt:
    name: xfsprogs
    state: present
  when: ai_filesystem == "xfs"
  become: yes

- name: Install filesystem utilities for Btrfs
  apt:
    name: btrfs-progs
    state: present
  when: ai_filesystem == "btrfs"
  become: yes

- name: Create benchmark results directory
  file:
    path: "{{ ai_benchmark_results_dir }}"
    state: directory
    mode: '0755'
  become: yes
