---
distro_debian_based: false
virtbuilder_os_version: "debian-13-generic-amd64-daily"

libvirt_uri_system: false
libvirt_enable_largeio: false
bootlinux_9p: false
kdevops_workflow_enable_minio: false
kdevops_workflow_enable_tcg_storage: false
