---
- ansible.builtin.include_role:
    name: pkg

# tasks to install dependencies for vLLM
- name: vLLM distribution specific setup
  ansible.builtin.import_tasks: tasks/install-deps/debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'
- ansible.builtin.import_tasks: tasks/install-deps/suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'
- ansible.builtin.import_tasks: tasks/install-deps/redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
