---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Stop and remove Milvus container
  community.docker.docker_container:
    name: "{{ ai_milvus_container_name }}"
    state: absent
  when: ai_milvus_docker | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Stop and remove MinIO container
  community.docker.docker_container:
    name: "{{ ai_minio_container_name }}"
    state: absent
  when: ai_milvus_docker | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Stop and remove etcd container
  community.docker.docker_container:
    name: "{{ ai_etcd_container_name }}"
    state: absent
  when: ai_milvus_docker | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Remove Docker network
  community.docker.docker_network:
    name: "{{ ai_docker_network_name }}"
    state: absent
  when: ai_milvus_docker | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Clean up Python packages (optional)
  ansible.builtin.pip:
    name:
      - pymilvus
      - matplotlib
      - seaborn
      - plotly
    state: absent
  when: ai_benchmark_enable_graphing | bool
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Display uninstall completion message
  ansible.builtin.debug:
    msg: |
      AI benchmark components uninstalled successfully.
      Data directories preserved:
      - {{ ai_docker_data_path }}
      - {{ ai_benchmark_results_dir }}

      To completely remove all data, run the ai-destroy target.
