---
# Test taking ownership of TCG device

- name: Check device exists
  ansible.builtin.stat:
    path: "{{ tcg_storage_test_device }}"
  register: device_stat

- name: Fail if device doesn't exist
  ansible.builtin.fail:
    msg: "Device {{ tcg_storage_test_device }} does not exist"
  when: not device_stat.stat.exists

- name: Test take ownership operation
  block:
    - name: Note about take-ownership
      ansible.builtin.debug:
        msg: "Note: sedlockctl doesn't have a take-ownership command. Testing list functionality instead."

    - name: List device ranges (ownership test alternative)
      ansible.builtin.command: >
        sedlockctl --password {{ tcg_storage_test_password }}
        {{ tcg_storage_test_device }} list
      register: ownership_result
      become: yes
      ignore_errors: yes

    - name: Try device info with tcgdiskstat
      ansible.builtin.command: >
        tcgdiskstat {{ tcg_storage_test_device }}
      register: status_result
      become: yes
      ignore_errors: yes

    - name: Save ownership test results
      ansible.builtin.copy:
        content: |
          Take Ownership Test Results
          ===========================
          Date: {{ ansible_date_time.iso8601 }}
          Host: {{ inventory_hostname }}
          Device: {{ tcg_storage_test_device }}

          Take Ownership Output:
          {{ ownership_result.stdout }}

          Device Status After:
          {{ status_result.stdout }}
        dest: "{{ tcg_storage_results_dir }}/ownership_test_{{ inventory_hostname }}.txt"
      delegate_to: localhost

    - name: Display test results
      ansible.builtin.debug:
        msg: |
          Take ownership test completed.
          Result: {{ 'SUCCESS' if ownership_result.rc == 0 else 'FAILED' }}
  when: test_take_ownership|bool