---
# Install dependencies for monitoring on Debian

- name: Update apt cache
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install monitoring Python dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - python3-matplotlib
      - python3-packaging
      - python3-numpy
      - python3-bpfcc
    state: present
  when:
    - enable_monitoring|default(false)|bool

- name: Install folio migration monitoring dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - python3-psutil
    state: present
  when:
    - enable_monitoring|default(false)|bool
    - monitor_folio_migration|default(false)|bool

- name: Install memory fragmentation monitoring dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - python3-scipy
    state: present
  when:
    - enable_monitoring|default(false)|bool
    - monitor_memory_fragmentation|default(false)|bool
