---
- name: Run Milvus Vector Database Benchmarks
  hosts: ai
  vars:
    ai_vector_db_milvus_benchmark_enable: true
  roles:
    - role: milvus
      tags: ['ai', 'vector_db', 'milvus', 'benchmark']
