---
- name: Enable fstests JUnit XML result processing
  hosts: localhost
  roles:
    - role: fstests_prep_localhost

- name: Set up NFS server with iSCSI target for pNFS
  hosts: nfsd
  roles:
    - role: iscsi
  when: fstests_nfs_section_pnfs|default(false)|bool

- name: Configure and run the filesystem testing suite workflow
  hosts: baseline:dev
  roles:
    - role: fstests
