# SPDX-License-Identifier copyleft-next-0.3.1
---
# There are from other roles but we must define hese here for correctness
# They will be overridden by generated extra_vars.yaml in kdevops
data_path: "/data"
target_linux_tree: "linux-stable"
target_linux_dir_path: "{{ data_path }}/{{ target_linux_tree }}"
bootlinux_9p_host_path: "/home/user/linux/"

# These are selftests specific
kdevops_workflow_enable_selftests: False
kdevops_run_selftests: False
run_tests_on_failures: False
selftests_skip_run: False
selftests_skip_reboot: False
selftests_build_radix_tree: False
selftests_build_selftests_dir: False
selftests_radix_tree_dir: "tools/testing/radix-tree"

selftests_section_firmware: False
selftests_section_kmod: False
selftests_section_maple: False
selftests_section_sysctl: False
selftests_section_xarray: False
selftests_section_vma: False

selftests_ksrc: "tools/testing/selftests/"
selftests_data: "{{ target_linux_dir_path }}/{{ selftests_ksrc }}"
selftests_data_9p: "{{ bootlinux_9p_host_path }}/{{ selftests_ksrc }}"
selftests_data_target: "{{ data_path }}/selftests/"
selftests_workdir: "{{ selftests_data_target }}/kselftest/kselftest_install/"
selftest_timeout_argument: ""

selftest_userspace: False
selftest_kernelspace: False

selftest_xarray: False
selftest_maple: False
selftest_vma: False
