---
galaxy_info:
  author: kdevops AI team
  description: Milvus vector database installation and setup for AI workflows
  company: kdevops
  license: copyleft-next-0.3.1
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - ai
    - vector_database
    - milvus
    - machine_learning

dependencies: []
